# List of known platforms
platforms = {
    'illumina': 'Illumina',
    '454': 'LS454',
    'torrent': 'Ion Torrent',
    'solid': 'ABI SOLiD',
}
# 'preset': (country, region, city, zip, longitude, latitude, note)
location_hash = {
    'missing': ('', '', '', '', '', '', ''),
    'unknown': ('', '', '', '', '', '', ''),
    'na':      ('', '', '', '', '', '', ''),
    'egypt':   ('Egypt', '', '', '', 30.7956597, 26.8357675, 'egypt'),
    'usa:or':  (
        'United States',
        'Oregon',
        '',
        '',
        -120.5380993,
        44.1419049,
        'USA:OR'
    )
}

ontology = [
    ('other',  ['environmental', 'enviromental', 'soil', 'fines',
                'painting', 'railing', 'prebiotic', 'dust', 'lagoon',
                'washroom', 'crate', 'fertilizer', 'rubber', 'broom', 'waste',
                'pet treat', 'dog food', 'pet food', 'chews', 'metal',
                'tinfoil',
                'bathroom', 'manufacture', 'septic tank', 'kitten food',
                'facility', 'plastic', 'kennel', 'psyllium', 'bedding',
                'floor',
                'sponge stick', 'packaging', 'cage', 'feed', 'drag swab',
                'arnica montana', 'kitchen', 'cat food', 'catfood',
                'cat\'s claw',
                'comminuted', 'cotton', 'belt', 'egg pool', 'dog chew']),
    ('food',   ['food', 'fenugreek', 'seed', 'fresh', 'frozen', 'frz', 'tahin',
                'basil', 'meat', 'dried', 'sage', 'powder', 'cantaloupe',
                'meal',
                'tempeh', 'chile', 'milk', 'mushroom', 'ground', 'cooked',
                'egg',
                'cucumber', 'kabob', 'cheese', 'oregano', 'rosemary',
                'baklava',
                'chocolate', 'marjoram', 'asafoetida', 'meringue', ' raw',
                'raw ',
                'seafood', 'mix', 'cardamon', 'hamburger', 'spic', 'salt',
                'radish', 'pepper', 'pistachio', 'dry', 'slice', 'cube',
                'crab',
                'whey', 'spinach', 'butter', 'fried', 'kasuri methi', 'minced',
                'frog leg', 'pork', 'artichoke', 'calonji', 'fillet', 'noodle',
                'herbs', 'diced', 'mouloukhia', 'grated', 'almond', 'avocado',
                'leaves', 'boiled', 'cilantro', 'biscuit', 'carrageenan',
                'charoli', 'halva', 'amaranth', 'barley drink', 'pesto',
                'fruit',
                'puffed', 'masala', 'shredded', 'tea', 'lettuce', 'nut',
                'mango',
                'cream', 'origanum', 'tomoato', 'celery', 'toast', 'leaf',
                'dal',
                'tomato', 'verde', 'papaya', 'halawa', 'organic', 'snack',
                'soy',
                'chilli', 'giblets combo', 'cake', 'salami', 'paprika',
                'paste',
                'pecan', 'cumin', 'yeast', 'sesame', 'beef', 'vanilla',
                'saku block', 'root', 'diet', 'chamomile', 'queso',
                'sunflower',
                'parsley', 'dehydrat', 'onion', 'culantro', 'papdi', 'cashew',
                'turmeric', 'falafel', 'cereal', 'coriander', 'thyme', 'filet',
                'flour', 'lasagna', 'roast', 'foxtail millets', 'tuna block',
                'broiled', 'dumpling', 'broccoli', 'cordon bleu',
                'cordon blue',
                ' thigh', ' drumsticks', ' breast', 'kiev', 'smoked', ' tail',
                'popcorn', 'stuffed', 'jerky']),
    ('animal', ['animal', 'bird', 'mammal', 'fish', 'pig', 'seagull', 'avian',
                'turtle', 'bovine', 'porcine', 'cat', 'fusilier', 'snapper',
                'bat', 'pabda', 'threadfin', 'python', 'swine', 'feline',
                'lamb',
                'equine', 'octopus', 'deer', 'duck', 'ovine', 'popano', 'bass',
                'chichen', 'tilapia', 'red nilotica', 'cervid', 'finch',
                'gecko',
                'redgull', 'tortoise', 'caprine', 'monitor', 'camelid',
                'snake',
                'rodent', 'camel', 'cow', 'bata', 'dog', 'wolverine', 'equine',
                'frog', 'mrigal', 'sparrow', 'gizzards', 'siskin', 'canine',
                'mink', 'rohu', 'horse', 'alpaca', 'moose', 'reptile',
                'cattle',
                'baim', 'felien', 'skink', 'chukar', 'lizard', 'sheep',
                'perch',
                'redpoll', 'eel', 'lion', 'scad', 'monkey', 'elk', 'llama',
                'hamster', 'batashi', 'raccoon', 'mouse', 'poultry', 'rabbit',
                'racoon', 'scallop', 'hilsa', 'shrimp', 'pomfret', 'pompfret',
                'snail', 'chicken', 'turkey', 'anchovy', 'squid', 'tuna',
                'mahi',
                'lobster', 'mackerel', 'barramundi', 'iguana', 'carcass',
                'amphibian', 'toad', 'bivalve', 'serpent', 'salamander',
                'trachemys scripta', 'prawns', 'sternotherus odoratus']),
    ('water',  ['water', 'pond', 'sediment', 'sea', 'irrigation']),
    ('food',   ['corn', 'chip', 'sprout']),
    ('human',  ['human', 'feces', 'fecal', 'stool', 'blood', 'fluid', 'urine',
                'clinical', 'aspirate', 'tissue', 'patient', 'wound', 'liver',
                'rectal']),
    ('laboratory',  ['bacterial']),
    ('other',  ['other', 'farm', 'fan', 'swab', 'bag', 'gum', 'produc', 'air',
                'surface']),
    ('unknown', ['unknown', 'missing', 'na', 'sentiment', 'rupsha', 'sample',
                 'isolate'])
]
